main: customEnchants.TestEnchants
version: 1.0.0-SNAPSHOT
name: TestEnchants
author: Zach
api-version: 1.13

softdepend: [Vault]
depend: [WorldGuard]


commands:
  scrap:
    description: Opens the scrap GUI
  giveenchant:
    description: Gives a custom enchanted book
    permission: customEnchants.admin
  giveCustomItem:
    description: Gives a custom utility item
    permission: customEnchants.giveCustomItem
  keyall:
    description: Give Key All Voucher to all players
    usage: /keyall
    permission: customEnchants.admin
  claim:
    description: Opens Claim menu
    usage: /claim
  extractor:
    description: Opens extractor menu
    usage: /extractor
  essence:
    description: Opens the Essence Menu GUI
    usage: /essence
  rankup:
    description: rankup
    usage: /rankup
  setrank:
    description: Set a player's rank.
    usage: /setrank <player> <rank>
    permission: customEnchants.admin
  essencenotif:
    description: Enables or disables essence notifications
    usage: /essencenotif
  resetmine:
    description: Resets a mine
    usage: /resetmine <mine name>
    permission: customEnchants.admin
  pv:
    description: Open your player vault
    usage: /pv <1-5>
  pvsee:
    description: Admin view of other players' vaults
    usage: /pvsee <player> <1-5>
    permission: customenchants.admin
  sell:
    description: Sell items
    usage: /sell [hand|all]
  quest:
    description: Opens the quest GUI
    aliases: [q]
  completequest:
    usage: /completequest <1|2> <player>
    description: Force complete a player's quest
    permission: customenchants.admin
  nightvision:
    usage: /nightvision
    description: gives nightvision
    aliases: [nv]
  spawntrader: 
    usage: /spawntrader [deep|essence]
    description: spawns a trading villager
    permission: customenchants.admin
  savewarp:
    usage: /savewarp [warp name]
    description: saves a warp for mine Resets
    permission: customenchants.admin
  removewarp:
    usage: /removewarp [warp name]
    description: removes a warp for mine Resets
    permission: customenchants.admin