main: customEnchants.TestEnchants
version: 1.0.0-SNAPSHOT
name: TestEnchants
author: Zach
api-version: 1.13

commands:
  scrap:
    description: Opens the scrap GUI
  giveenchant:
    description: Gives a custom enchanted book
  giveCustomItem:
    description: Gives a custom utility item
  testblackscroll:
    description: opens Black Scroll Gui
  keyall:
    description: Give Key All Voucher to all players
    usage: /keyall
    permission: customenchants.keyall