main: customEnchants.TestEnchants
version: 1.0.0-SNAPSHOT
name: TestEnchants
author: Zach
api-version: 1.13

softdepend: [Vault]

commands:
  scrap:
    description: Opens the scrap GUI
  giveenchant:
    description: Gives a custom enchanted book
    permission: customEnchants.giveenchant
  giveCustomItem:
    description: Gives a custom utility item
    permission: customEnchants.giveCustomItem
  keyall:
    description: Give Key All Voucher to all players
    usage: /keyall
    permission: customEnchants.keyall
  claim:
    description: Opens Claim menu
    usage: /claim
  extractor:
    description: Opens extractor menu
    usage: /extractor
  essence:
    description: Opens the Essence Menu GUI
    usage: /essence
  rankup:
    description: rankup
    usage: /rankup
  setrank:
    description: Set a player's rank.
    usage: /setrank <player> <rank>
    permission: customEnchants.setrank
  essencenotif:
    description: Enables or disables essence notifications
    usage: /essencenotif
